
spring:

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    initialization-mode: never
    url: jdbc:mysql://localhost:3306/basket_App
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
server:
  port: 8001
  servlet:
    context-path: /api
